### ISSUE TITLE
horizontal scrolling 

### ISSUE THREAD

**Issue by Polimac** [marcokreeft87/room-card#53] opened 2022-09-18 12:15 UTC
hi again me :)

i got horizontal scrolling issue in app on mobile , when your card is in dashboard
i am able to move horizontally screen

![2022-09-18 14 13 51](https://user-images.githubusercontent.com/16742142/190901551-c0111c41-d5e4-4486-8bd7-74ae0a94a3c0.jpg)

code

type: custom:room-card
title: Livingroom
rows:
  - entities:
      - entity: light.livingroom_ceiling
        name: Livingroom ceiling
        icon: mdi:ceiling-light
        tap_action:
          action: toggle
      - entity: light.0x00124b0022727206
        name: Livingroom Ambient
        icon: mdi:led-strip
        tap_action:
          action: more-info
      - entity: light.livingroomspotlight
        name: Livingroom Spot
        icon: mdi:track-light
        tap_action:
          action: toggle
      - entity: light.wc_pathway
        name: WC Pathway
        icon: mdi:lightbulb
        tap_action:
          action: toggle
  - entities:
      - entity: light.kitchen_spot_1
        name: Kitchen Spot 1
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.kitchen_spot_2
        name: Kitchen Spot 2
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.kitchen_led
        name: Kitchen Led
        icon: mdi:led-strip
        tap_action:
          action: toggle
  - entities:
      - entity: light.wc_ceiling
        name: WC Ceiling
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.wc_mirror
        name: WC Mirror light
        icon: mdi:led-strip-variant
        tap_action:
          action: toggle
      - entity: switch.0x5c0272fffe1cae01_l1
        name: WC Ventilation
        icon: mdi:fan
        state_color: true
        tap_action:
          action: toggle
  - entities:
      - entity: light.doorwaygrouplight
        name: Doorway
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
      - entity: light.hallway
        name: Hallway
        icon: mdi:ceiling-light-multiple
        tap_action:
          action: toggle
  - entities:
      - entity: cover.0xa4c13862a3c38fec
        name: Shade
        tap_action:
          action: toggle
        state_color: true
      - entity: fan.0xb4e3f9fffe2b20e6
        name: Airpurifier
        icon: mdi:air-filter
        tap_action:
          action: more-info
        state_color: true
info_entities:
  - entity: sensor.livingroomsensor_temperature
  - entity: sensor.livingroomsensor_humidity
  - entity: sensor.0xb4e3f9fffe2b20e6_pm25

**Comment by marcokreeft87** [comment] 2022-09-18 12:30
I think you have too many entities on one row

**Comment by marcokreeft87** [comment] 2022-09-19 06:40
Reading back my comment didnt make sense.  I think there is something that is waayy to wide for this view. Dont think this is because of the room card tho. Could be that it only happens when the card is being added. But everything in the card is nice and neat between the borders of the card in your screenshot. Isnt there something lower that is wider than the view?

**Comment by marcokreeft87** [comment] 2022-09-19 16:25
@mihsu81 can you make the names shorter? See if that helps

**Comment by mihsu81** [comment] 2022-09-20 05:17
@marcokreeft87 Doesn't seem to help. 
I've also removed the additional styling from the card.
![Screenshot_2022-09-20-08-14-59-53_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191173323-d09ba87e-41c2-4951-afeb-1f9305a05f93.jpg)

**Comment by marcokreeft87** [comment] 2022-09-20 05:59
Hmm and make rows of 5 entities max?

**Comment by marcokreeft87** [comment] 2022-09-20 06:07
And what's that weird bar to the right?

**Comment by marcokreeft87** [comment] 2022-09-20 12:04
Idk guys, I cant reproduce:
![image](https://user-images.githubusercontent.com/10223677/191252642-910b748e-64d7-44c2-ba3b-1a8612d066d0.png)
![image](https://user-images.githubusercontent.com/10223677/191252734-0db620cb-2154-4e8f-93f9-a237c9f89bb8.png)

```
type: custom:room-card
title: test
entity: light.mancave_lampen
icon: mdi:floor-lamp-outline
show_icon: true
tap_action:
  action: toggle
rows:
  - entities:
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
        tap_action:
          action: toggle
        hold_action:
          action: more-info
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
      - entity: light.mancave_lamp
        name: Plafond dfdfdfd fdfdfdsfdsfds
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
      - entity: light.mancave_lamp
        name: Plafond
  - entities:
      - entity: light.mancave_lamp
        name: Plafond
        tap_action:
          action: toggle
        hold_action:
          action: more-info

```

**Comment by Polimac** [comment] 2022-09-20 12:05
i think it is related to info_entities

**Comment by marcokreeft87** [comment] 2022-09-20 12:23
> i think it is related to info_entities

Can you reproduce with only info_entities?

**Comment by mihsu81** [comment] 2022-09-20 16:20
I've reduced the number of entities per row to 5 and the issue persists. 
The bar to the right is created by the HA app when  the size is higher. It's the same color as the upper frame.
![Screenshot_2022-09-20-19-17-20-09_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191311787-1a551697-b284-4579-a9e6-6fb77167a777.jpg)

**Comment by marcokreeft87** [comment] 2022-09-20 16:49
Hmm, can you try a different theme?

**Comment by mihsu81** [comment] 2022-09-20 16:58
The issue appears with the default theme as well.
The theme is https://github.com/tgcowell/waves.
![Screenshot_2022-09-20-19-56-17-78_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/40715497/191319280-3d97a664-1089-49d0-9063-ba2b346eaff0.jpg)

**Comment by marcokreeft87** [comment] 2022-09-20 17:01
Super weird. Share the yaml of that dashboard plz and I will try to reproduce. But since I see so many without this problem I'm inclined to say it's something in your settings. But let's see

**Comment by mihsu81** [comment] 2022-09-20 17:51
```yaml
title: Home Dashboard
views:
  - title: Test room card
    path: test-room-card
    badges: []
    cards:
      - type: custom:room-card
        title: Kitchen
        entity: binary_sensor.area_kitchen
        icon: hue:room-kitchen
        state_color: true
        show_state: true
        show_icon: true
        column: false
        rows:
          - entities:
              - entity: light.kitchen_light
                name: Light
                icon: hue:pendant-cher
                state_color: true
                show_state: true
                show_icon: true
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
```
It does make sense that it's some card we have installed, but who knows which.
Here's a list of Frontend integrations I have installed which might be the cause, since thy deal with styling.
Stack In Card
Purifier Card
Vacuum Card
Config Template Card
Simple Weather Card
Vertical Slider Cover Card
KNX User Forum Icon Set
Simple Thermostat
badge-card
card-mod
BHA Icon Pack
bignumber-card
Custom brand icons
Vertical Stack In Card
mini-graph-card
Xiaomi Vacuum Map Card
Bar Card
card-tools
slider-entity-row
Mini Media Player
mini climate card
button-card
auto-entities
Hass Hue Icons
Alarmo Card
Waves
Body Miscale Card
Config Editor Card
Better Thermostat UI
history-explorer-card
Plotly Graph Card
Thermal Comfort Icons
Only Lock Lock Row
Flower Card
Nordic Theme
custom-icons
TV Remote Card (with touchpad and haptic feedback)
My Cards Bundle
Swiss Army Knife custom card
Valetudo Map Card
Room Card

**Comment by marcokreeft87** [comment] 2022-09-20 18:05
Hmm wild guess, since it's the horizontal space you have an issue with: Slider card?

Can you try without the slider card? Maybe it uses some classes room card also uses.

**Comment by mihsu81** [comment] 2022-09-21 06:05
Not all of these Frontend integrations are used in that View or in the Dashboard itself.
That Slider card is for cover entities. I've removed it and didn't make a difference.

**Comment by marcokreeft87** [comment] 2022-09-21 06:26
> Not all of these Frontend integrations are used in that View or in the Dashboard itself. That Slider card is for cover entities. I've removed it and didn't make a difference. I've created a new Dashboard and again the View can be moved to the left even though it shouldn't. Maybe we're taking the wrong approach in finding the issue, but again I don't really know which is the correct approach. 😁
> 
> New clean dashboard, recreated from scratch:
> 
> ```yaml
> views:
>   - title: Home
>     cards:
>       - type: custom:room-card
>         title: Kitchen
>         entity: binary_sensor.area_kitchen
>         icon: hue:room-kitchen
>         state_color: true
>         show_state: true
>         show_icon: true
>         column: false
>         rows:
>           - entities:
>               - entity: light.kitchen_light
>                 name: Light
>                 icon: hue:pendant-cher
>                 state_color: true
>                 show_state: true
>                 show_icon: true
>                 tap_action:
>                   action: toggle
>                 hold_action:
>                   action: more-info
> ```

Yeah I think we are taking the wrong approach. Because clearly im not gonna be able to reproduce..  There is a new version: 1.4.0. Can you try with that? And if that doesnt help at least we are on the same version.

**Comment by Polimac** [comment] 2022-09-21 06:35
i updated to 1.4
same issue
only show_icon: true is mandatory when you set icon

**Comment by marcokreeft87** [comment] 2022-09-21 06:37
> i updated to 1.4 same issue only show_icon: true is mandatory when you set icon

Yes thats in the release notes..

**Comment by mihsu81** [comment] 2022-09-21 07:45
The issue continues in v1.4

**Comment by marcokreeft87** [comment] 2022-09-21 08:28
I really can't reproduce. Sorry, but I think it's something with your settings or other themes/cards that you installed

**Comment by RadioLed2000** [comment] 2022-09-27 20:49
I have the same issue. This happens when I use rows option.

This config has no problems:
```type: custom:room-card
title: TEST1
entity: switch.hall_light
show_icon: true
state_color: true
tap_action:
  action: toggle
info_entities:
  - entity: sensor.bedroom_sensor_temperature
    format: precision1
  - entity: sensor.bedroom_sensor_humidity
    format: precision0
entities:
  - entity: switch.hall_lamp1
    name: lamp1
    state_color: true
    tap_action:
      action: toggle
  - entity: switch.hall_lamp2
    name: lamp2
    state_color: true
    tap_action:
      action: toggle
```

But the following config has horisontal scrolling:
```type: custom:room-card
title: TEST2
entity: switch.hall_light
show_icon: true
state_color: true
tap_action:
  action: toggle
info_entities:
  - entity: sensor.bedroom_sensor_temperature
    format: precision1
  - entity: sensor.bedroom_sensor_humidity
    format: precision0
rows:
  - entities:
      - entity: switch.hall_lamp1
        name: lamp1
        state_color: true
        tap_action:
          action: toggle
      - entity: switch.hall_lamp2
        name: lamp2
        state_color: true
        tap_action:
          action: toggle
```

Home Assistant 2022.9.6, default theme, android mobile app, each test card is on it's own tab

**Comment by hugalafutro** [comment] 2022-10-02 07:56
I can confirm this is tied to using the `rows:` option on my OnePLus 6T, Android 11, with default dark theme on HA 2022.9.7.
_Unrelated, but for what it's worth `double_tap_action` seems to act as `hold_action` on android, which I much prefer and would also love on the desktop._

As the poster above, easily reproduced by removing rows: from my card and re-adding it. Hopefully the author is able to reproduce it with this.

**Comment by marcokreeft87** [comment] 2022-10-02 08:38
> title: TEST2
> entity: switch.hall_light
> show_icon: true
> state_color: true
> tap_action:
>   action: toggle
> info_entities:
>   - entity: sensor.bedroom_sensor_temperature
>     format: precision1
>   - entity: sensor.bedroom_sensor_humidity
>     format: precision0
> rows:
>   - entities:
>       - entity: switch.hall_lamp1
>         name: lamp1
>         state_color: true
>         tap_action:
>           action: toggle
>       - entity: switch.hall_lamp2
>         name: lamp2
>         state_color: true
>         tap_action:
>           action: toggle

No I got it too! Thnx. I will try and fix it

**Comment by marcokreeft87** [comment] 2022-10-02 09:00
Ok I was being a donut. Found the issue, new version incoming

**Comment by marcokreeft87** [comment] 2022-10-02 09:02
v1.06.12 should fix this issue

**Comment by hugalafutro** [comment] 2022-10-02 09:13
Can confirm 1.06.12 fixed it after force closing ha app, cleaning it's cache and reopening. Thanks for quick fix!

**Comment by marcokreeft87** [comment] 2022-10-02 09:20
>

**Closed by marcokreeft87** 2022-10-02 09:20 UTC
