### ISSUE TITLE
Error: "Custom element doesn't exist" on builtin cards

### ISSUE THREAD

**Issue by rummik** [marcokreeft87/room-card#104] opened 2022-10-21 13:57 UTC
**Describe the bug**
There seems to be an issue with embedding builtin cards

**To Reproduce**
1. Create a `custom:room-card`
2. Add a sub-card using any builtin card (ex: picture-glance)
3. Click on 'save'
4. Reload the page
5. See error

Example YAML:
```yaml
type: custom:room-card
title: Kitchen
cards:
  - camera_view: live
    type: picture-glance
    title: Kitchen
    image: https://demo.home-assistant.io/stub_config/kitchen.png
    entities:
      - entity: sensor.uptime
```

**Expected behavior**
Custom room card should be visible with builtin card

**Screenshots**
![image](https://user-images.githubusercontent.com/630909/197212555-be8704c7-c735-4aae-a8bb-99242d018ee4.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 105.0.1

**Additional context**
Looks like this may be related to #64

**Comment by marcokreeft87** [comment] 2022-10-21 17:08
Working on my HA

![image](https://user-images.githubusercontent.com/10223677/197250977-72b7f5af-18b3-420e-aaa9-43859521853e.png)

**Comment by rummik** [comment] 2022-10-21 22:46
Current HA.  Have you saved and reloaded the dashboard?

**Comment by marcokreeft87** [comment] 2022-10-21 22:50
Ah on mobile I get it too. Weird, but I might know what's the problem

**Comment by marcokreeft87** [comment] 2022-10-21 22:51
Ah on mobile I get it too. Weird, but I might know what's the problem.

Edit: nope that isn't it

**Comment by rummik** [comment] 2022-10-21 23:04
I've poked at it a little bit the other day, but I don't know enough about how HA handles card loading to submit a fix 😅

At least it's relatively easy to reproduce I guess?

**Comment by marcokreeft87** [comment] 2022-10-21 23:08
It is easy to reproduce,  but since this is an error HA throws it a pain to debug

**Comment by marcokreeft87** [comment] 2022-10-22 07:42
Weird thing is, for example the "entities" card is working..

**Comment by rummik** [comment] 2022-10-26 19:35
I'm finding that it works if I have the builtin card I want loaded elsewhere on the dashboard.  If I can manage to find the time I'll dig around and see if I can get a PR, since I did notice there's an exposed API that doesn't seem to be used by the library you're using, and I'd like to compare what's being done differently

**Comment by marcokreeft87** [comment] 2022-10-26 19:39
That would be nice. Good find btw

**Comment by omayhemo** [comment] 2022-11-01 21:32
I have the same problem.

**Comment by omayhemo** [comment] 2022-11-02 17:29
FYI latest version I grabbed from HACS didn't solve, but you probably knew that already.

**Comment by marcokreeft87** [comment] 2022-11-02 17:30
> FYI latest version I grabbed from HACS didn't solve, but you probably knew that already.

Thats why there are release notes in them :P

**Comment by marcokreeft87** [comment] 2022-11-02 17:34
@omayhemo  Weird thing is, I had this error while developing 1.07.01 but its gone now

**Comment by omayhemo** [comment] 2022-11-02 17:36
ORLY?  I can't be arsed.  :)

**Comment by omayhemo** [comment] 2022-11-03 14:12
> @omayhemo Weird thing is, I had this error while developing 1.07.01 but its gone now

Since its WOM, I wonder if your local differs from the repo?

**Comment by omayhemo** [comment] 2022-11-03 17:40
I haven’t tried other browsers just edge, I’ll test others when I can. Just trying to provide a little data no idea if it helps you or not.

**Comment by omayhemo** [comment] 2022-12-19 15:30
Exists in all browsers, just FYI.  Furthermore, I get a a.style can't be on undefined error periodically as well.  Refreshes don't help, I have to go in and literally perform an edit on the card and save it and then the whole view will work.  There seems to be a rendering timing problem or something.  I have to find a different solution at this point.

**Comment by marcokreeft87** [comment] 2022-12-19 16:46
Unfortunately I can't test all cards. And tbf it's a nice extra feature, but cards will always work best in a seperate instance.

**Comment by csthomas2** [comment] 2023-02-08 02:47
I built a dashboard specifically for mobile with this card. I still get the a.style undefined and element doesn't exist. I temporarily fixed by adding the two built-in cards at the bottom, but I have to scroll all the way down then refresh the page for the a.style error to go away. Then I have to wait until the picture entity cards refresh by themselves for the undefined element to fix itself. I'm using latest versions of the card and HA.

**Comment by marcokreeft87** [comment] 2023-02-08 05:36
Can you share your yaml?

**Comment by csthomas2** [comment] 2023-02-09 01:30
Sure.
`  - theme: Backend-selected
    layout:
      width: 375
      max_cols: 1
    icon: mdi:cellphone
    subview: false
    type: custom:masonry-layout
    badges: []
    cards:
      - type: custom:room-card
        title: Den
        entity: light.den_hue
        show_icon: true
        icon: mdi:lightbulb-outline
        state_color: true
        tap_action:
          action: toggle
        info_entities:
          - entity: binary_sensor.tv_entertainment_configuration
            show_icon: true
            state_color: true
            icon: mdi:bluetooth-audio
        rows:
          - entities:
              - entity: scene.den_memento
                name: Memento
                tap_action:
                  action: call-service
                  service: hue.activate_scene
                  service_data:
                    dynamic: true
                  target:
                    entity_id: scene.den_memento
              - entity: scene.den_nightlight
                name: NightLight
                tap_action:
                  action: call-service
                  service: hue.activate_scene
                  service_data:
                    dynamic: true
                  target:
                    entity_id: scene.den_nightlight
              - entity: scene.den_bright
                name: Bright
                tap_action:
                  action: call-service
                  service: hue.activate_scene
                  service_data:
                    dynamic: true
                  target:
                    entity_id: scene.den_bright
              - entity: scene.den_relax
                name: Relax
                show_icon: true
                tap_action:
                  action: call-service
                  service: hue.activate_scene
                  service_data:
                    dynamic: true
                  target:
                    entity_id: scene.den_relax
          - entities:
              - entity: light.hue_color_lamp_1_4
                name: Lamp
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.lg_tv
                name: TV
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.den_fan_light
                name: Fan
                show_icon: true
                icon: mdi:lightbulb
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.chris_go
                name: Go
                show_icon: true
                icon: mdi:lightbulb
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
          - entities:
              - entity: media_player.lg_tv
                name: HDMI 1
                show_icon: true
                double_tap_action:
                  action: none
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: HDMI 1
                  target:
                    entity_id: media_player.lg_tv
                icon: mdi:laptop
                content: ''
                hold_action:
                  action: none
              - entity: media_player.lg_tv
                name: HDMI 2
                show_icon: true
                double_tap_action:
                  action: none
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: SHIELD Game Console
                  target:
                    entity_id: media_player.lg_tv
                icon: mdi:android
                content: ''
                hold_action:
                  action: none
              - entity: media_player.lg_tv
                name: HDMI 3
                show_icon: true
                double_tap_action:
                  action: none
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: HDMI 3
                  target:
                    entity_id: media_player.lg_tv
                icon: ''
                content: HDMI3
                hold_action:
                  action: none
              - entity: media_player.lg_tv
                name: HDMI 4
                show_icon: true
                double_tap_action:
                  action: none
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    source: HDMI 4
                  target:
                    entity_id: media_player.lg_tv
                icon: ''
                content: HDMI4
                hold_action:
                  action: none
      - type: custom:room-card
        title: Front Room
        entity: light.front_room
        show_icon: true
        icon: mdi:lightbulb-outline
        state_color: true
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        cards:
          - entity: camera.doorbell_medium
            type: picture-entity
            show_state: false
            show_name: false
        info_entities:
          - entity: lock.front_door
            show_icon: true
            state_color: true
            tap_action:
              action: toggle
          - entity: sensor.main_floor_current_temperature
        rows:
          - entities:
              - entity: light.dabby
                name: Dabby
                state_color: true
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.kitchen_fan_light
                name: Kitchen Fan Light
                state_color: true
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: switch.node_5
                name: Kitchen Light
                state_color: true
                show_icon: true
                icon: mdi:lightbulb
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
              - entity: light.living_room_light
                name: Living Room Light
                state_color: true
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
          - entities:
              - entity: switch.living_room_fish_tank
                name: Fish Tank
                show_icon: true
                state_color: true
                icon: mdi:power-plug
                tap_action:
                  action: toggle
                hold_action:
                  action: more-info
      - type: custom:room-card
        title: Garage
        entity: switch.in_wall_smart_switch
        show_icon: true
        icon: mdi:lightbulb-outline
        state_color: true
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-entity-card
                entity: binary_sensor.garage_motion
                secondary_info: last-changed
                layout: vertical
              - type: custom:mushroom-entity-card
                entity: binary_sensor.g4_instant_motion
                secondary_info: last-changed
                layout: vertical
          - type: horizontal-stack
            cards:
              - entity: camera.garage_medium
                type: picture-entity
                show_state: false
                show_name: false
              - entity: camera.g4_instant_medium
                type: picture-entity
                show_state: false
                show_name: false
          - entity: camera.backyard_medium
            type: picture-entity
            show_state: false
            show_name: false
        info_entities:
          - entity: binary_sensor.garage_motion
            show_icon: true
            state_color: true
          - entity: binary_sensor.g4_instant_motion
            show_icon: true
            state_color: true
          - entity: binary_sensor.g4_instant_person_detected
            show_icon: true
            state_color: true
      - type: horizontal-stack
        cards:
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: none
            hold_action:
              action: none`

**Comment by csthomas2** [comment] 2023-02-09 01:32
[yaml.yaml.txt](https://github.com/marcokreeft87/room-card/files/10691659/yaml.yaml.txt)

**Comment by marcokreeft87** [comment] 2023-02-09 07:59
> Sure [yaml.yaml.txt](https://github.com/marcokreeft87/room-card/files/10691661/yaml.yaml.txt)

I think the problem here is that you put cards in a horizontal stack in a room card.

**Comment by csthomas2** [comment] 2023-02-09 12:28
I removed the horizontal-stacks from the room-cards and loaded the dashboard up in an incognito window. I first get this error (got this before as well). Then the page reloads itself (in incognito, I have to sign in again). Then I proceed to get the "Custom element doesn't exist". I would also get the "Custom element doesn't exist" for the horizontal-stack. Scrolling down and waiting eventually loads my horizontal stacks and the pictures within. The pictures do end up loading without the horizontal-stack as welll, since I have the extra card at the bottom.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/62066498/217812016-01674ba2-b2a6-40b6-b29e-c5eedc014551.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/62066498/217812630-433a3e03-c474-4e99-b364-10d982f5d208.png">

**Comment by marcokreeft87** [comment] 2023-02-09 12:45
Hmm some cards of HA work different from the others. For example the picture entity. But you now get the error like the rest in this topic.  I will take the horizontal-card into the test when I finally find the solution to this bug :)

**Comment by ADoby** [comment] 2023-02-28 19:47
Not sure if this is helpfull but this problem also happens when I nest the mushroom card inside the room card.
When I reload the dashboard in chrome or when restarting the android app I get either this:
![image](https://user-images.githubusercontent.com/3531972/221962200-16bfc842-2f6e-4526-b801-ddb510644cf6.png)
or
![image](https://user-images.githubusercontent.com/3531972/221962404-f245c6ad-7ec5-4415-a65e-a5bb25d70063.png)
Room cards without nested cards work fine and the mushroom card by itself also works fine.

**Comment by marcokreeft87** [comment] 2023-02-28 20:05
Why would you put the mushroom card in a room card? Thats just weird haha. But you have this error because you dont pass any entities to the room card

**Comment by ADoby** [comment] 2023-03-01 06:57
**"Why would you put the mushroom card in a room card?"**
Because I want to categorize my entities by room, I thought this is the meaning of the room/entities/auto entities cards.
Create one room card and then add all the entities that are inside that room inside the room card.
This way it's just a little bit faster and nicer looking to change the brightness or change the cover position.

**"But you have this error because you dont pass any entities to the room card"**
Doesn't seem so. I have multiple room cards in my dashboard every card that doesn't contain "cards:" works fine.
As soon as I add a single nested mushroom card it breaks the room card.

I tested nesting the build in light card and it works. 
At least for me it happens for custom cards, not build in cards even though I haven't tested all of them.

I did change the entitiy ids in the screenshot.
The screenshot only shows one of the possible errors, the other one "custom element doesn't exist" still also happens randomly.
![image](https://user-images.githubusercontent.com/3531972/222064022-4242625d-42c0-473b-aced-b384255f8e94.png)

**Comment by marcokreeft87** [comment] 2023-03-01 06:59
Ah ok. I think this will help. It gives me a direction to search for at least. Thanks for trying multiple configurations

**Comment by marcokreeft87** [comment] 2023-03-01 07:20
@ADoby  can you provide me with the yaml. Because I'm not getting the error 

![image](https://user-images.githubusercontent.com/10223677/222070719-2a117b9c-fce3-41c6-8cd9-af95902a4ea7.png)

**Comment by ADoby** [comment] 2023-03-01 07:30
Sure:
```
type: custom:room-card
title: Room
icon: mdi:lightbulb-outline
cards:
  - type: custom:mushroom-cover-card
    entity: cover.shelly_shsw_25_
```
    
Just to clarify, this error does not happen in the preview.
The preview always works.

It only happens when you finish editing the dashboard and then reload the page.
Then it randomly shows one of the two errors or it can also work randomly.

Here in preview
![image](https://user-images.githubusercontent.com/3531972/222072671-ac2cd544-3143-43c0-be60-1cfee5608f96.png)

Then randomly one of the errors when reloading the dashboard
![image](https://user-images.githubusercontent.com/3531972/222072024-c8e87a07-fea0-4d91-b729-7b2f1efc1e37.png)

or
![image](https://user-images.githubusercontent.com/3531972/222072140-13dc2a93-18da-45e2-a24f-f61508f62c16.png)

or it works
![image](https://user-images.githubusercontent.com/3531972/222072223-3e3786d4-772b-4973-891a-83d55197e302.png)

**Comment by marcokreeft87** [comment] 2023-03-01 07:36
Ah after a few refreshes I got it too! Nice now I can hopefully fix it

**Comment by ADoby** [comment] 2023-03-01 07:37
I have more details.
Every time it works the room card is loaded after the mushroom card.
![image](https://user-images.githubusercontent.com/3531972/222074031-fa895503-3852-46f1-b040-7b016e35b290.png)

When it doesn't work loading order is different.
![image](https://user-images.githubusercontent.com/3531972/222074091-b4d9aea7-0cb8-40b8-8d26-fbe682e06db6.png)

**Comment by marcokreeft87** [comment] 2023-03-01 07:57
Yeah I found the problem. Its in a npm package I use. 
The line that gives the error is : https://github.com/custom-cards/custom-card-helpers/blob/21546a17a667c969738ddb5c80feb1b65e569c69/src/create-thing.ts#L90
But its timing related.  If the card is loaded, it works. But sometimes the room card gets loaded before the included card

**Comment by marcokreeft87** [comment] 2023-03-01 08:07
Note to self : This might be the solution 

customElements.whenDefined(cardConfig.type).then(() => {
    clearTimeout(timer);
    fireEvent(element, "ll-rebuild", {}, element);
  });

**Comment by elninosi** [comment] 2023-04-07 11:39
After Home Assistant 2023.4 I'm constantly having this issue. Problem is in nested cards, e.g. cards inside room-card.
![image](https://user-images.githubusercontent.com/11082452/230602647-29f2e682-4e3b-42f3-9a52-21cf68816d5f.png)

Please let me know if any yaml codes from dashboard would help you with debugging the problem. 
Thanks.

**Comment by cookie050** [comment] 2023-05-07 17:29
Same problem

**Comment by mdecourcy** [comment] 2023-05-25 00:51
Any updates to this issue? I also experience this

**Comment by labaland** [comment] 2023-06-01 22:09
i have error alot, but if i save it it is correct and showing. false errors xD

**Comment by marcokreeft87** [comment] 2023-06-16 07:23
Just a little update from my end. Still trying to fix this but its a really tricky timing issue and since I'm working fulltime and I've got baseball in the weekends, I havent got that much time left

**Comment by cookie050** [comment] 2023-06-16 14:27
Will you be open for some help? I can have a look but don't know if i can fix it but can give it a try.

**Comment by marcokreeft87** [comment] 2023-06-20 18:43
@rummik @omayhemo @ADoby @elninosi @cookie050 @mdecourcy Can you guys try 1.07.24 and check if it's fixed now?

**Comment by ADoby** [comment] 2023-06-20 19:35
@marcokreeft87 
For me it doesn't help.
Same error as before.
"Cannot read property of undefined"
Tested from the mobile app and mobile browser.
Only happens when the dashboard with room cards is the default one.
When it first loads another dashboard and then you switch to the one with room cards it loads fine.

I made sure to close the app multiple times and check that the version 1.07.24 is installed.
I did not yet restart home assistant.

**Comment by mdecourcy** [comment] 2023-06-21 00:45
Issue seems to be resolved for me on my android. I will test further later tonight

**Comment by elninosi** [comment] 2023-06-21 05:12
Unfortunately issue is stil there.

**Comment by cookie050** [comment] 2023-06-21 13:53
In app, still same problem. If i change webviewer on android to chrome it works

**Comment by marcokreeft87** [comment] 2023-06-21 17:14
Crap @paulonutor seems like your solution doesn't seem to work for everyone. Can you check my note to self solution?

**Comment by paulonutor** [comment] 2023-06-21 18:03
My PR fixed something else. Nested entities didn't update on state change. This bug seems interesting and I'm going to take a look at it.

**Comment by elninosi** [comment] 2023-06-26 16:58
Looks like some elements are loaded before room card's code and this is causing a problem on slow mobile connection dashboard is almost always loaded properly.

**Comment by paulonutor** [comment] 2023-06-27 18:38
Could anyone check if it was fixed by #248 ?

**Comment by elninosi** [comment] 2023-06-27 18:51
@paulonutor I can't see that there are any updates available (current version 1.07.24).

**Comment by marcokreeft87** [comment] 2023-06-27 19:16
I need to make a release for that. But I have to review it first

**Comment by marcokreeft87** [comment] 2023-06-30 06:42
@elninosi I've made a new release, can you try now?

**Comment by elninosi** [comment] 2023-06-30 06:55
No errors are shown on the front-end on companion app for Android. Some
cards are not shown. Will try to debug in the following days and report as
much info as I can get.

V V pet., 30. jun. 2023 ob 08:42 je oseba Marco Kreeft <
***@***.***> napisala:

**Comment by ADoby** [comment] 2023-06-30 15:41
Home Assistant didn't show me any update, so I clicked on the redownload button in the options menu which let me select the .25 version and install it.

I have the same errors like before
- Cannot read properties of undefined
- Custom element doesn't exist
Randomly one of them or rarely it will work.
Both in the mobile app and desktop browser (chrome)
Also cleared the browser cache for the website.


I did not yet restart Home Assistant yet.
Do I need to restart to check if it works?

**Comment by elninosi** [comment] 2023-07-14 08:23
It looks like the problem is in one of the libraries.

Uncaught TypeError: a is undefined
>

 When I'm throttling internet connection everything is loaded properly. So
looks like dependencies are no loaded quickly enough.



V V pet., 30. jun. 2023 ob 17:41 je oseba ADoby ***@***.***>
napisala:

**Comment by marcokreeft87** [comment] 2023-10-13 09:33
I havent had this in a while now. Anyone in here who has had it since the october release?

**Comment by marcokreeft87** [comment] 2023-10-14 11:28
@elninosi Can you try with the new release?

**Comment by cookie050** [comment] 2023-10-14 11:57
Use latest update,  and still got this error. Before the update i modified it a little bit that if it errors it reloads. Not perfect and loop sensitive but it worked

**Comment by marcokreeft87** [comment] 2023-10-14 12:01
> Use latest update,  and still got this error. Before the update i modified it a little bit that if it errors it reloads. Not perfect and loop sensitive but it worked

Can you share your yaml?

**Comment by cookie050** [comment] 2023-10-14 12:03
It js but i can look in backup if i can find it. It updated and i forgot to pull the js before updating.

**Comment by marcokreeft87** [comment] 2023-10-14 12:08
I mean your yaml of the Configuration in HA

**Comment by cookie050** [comment] 2023-10-14 12:10
But the error and yaml,

Cannot read properties of undefined (reading 'style')
```
type: custom:room-card
title: Overloop & Sanitair
style: []
cards:
  - type: vertical-stack
    cards:
      - square: true
        columns: 4
        type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lamp_hal_boven
            name: Hal boven
            icon: mdi:ceiling-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lamp_hal_voordeur
            name: Hal beneden
            icon: mdi:ceiling-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lamp_overloop_z
            name: Overloop
            icon: mdi:ceiling-light
          - show_name: true
            show_icon: true
            type: button
            entity: switch.lamp_zolder_switch
            tap_action:
              action: toggle
            name: Zolder
            icon: mdi:ceiling-light
  - type: vertical-stack
    cards:
      - square: true
        columns: 4
        type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lamp_badkamer
            name: Badkamer
            icon: mdi:ceiling-light
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.lumi_lumi_switch_l1aeu1_light
            icon: mdi:ceiling-light
            name: Toilet
```

**Comment by marcokreeft87** [comment] 2023-10-14 12:18
But why do you use room-card for this?  You are using room-card like a container now, and not where it is designed for: Showing entities per room

**Comment by marcokreeft87** [comment] 2023-10-14 13:04
Doesn't take away the fact that it should work btw

**Comment by marcokreeft87** [comment] 2023-10-14 19:00
@cookie050  can you test it with v1.08.00 thanks to Scott ( don't know your github handle bro ) it should be fixed :)

**Comment by cookie050** [comment] 2023-10-14 19:07
Seem to do the trick, have used it on multiple devices all work in one time now :)

**Comment by marcokreeft87** [comment] 2023-10-14 19:09
> Seem to do the trick, have used it on multiple devices all work in one time now :)

Finally! Haha thanks for testing

**Closed by marcokreeft87** 2023-10-14 19:09 UTC
Labels: bug

**Comment by marcokreeft87** [comment] 2023-10-14 19:51
@rummik can you test this?

**Comment by mdecourcy** [comment] 2023-10-14 19:52
Works for me across several devices so far

**Comment by NeonOby** [comment] 2023-10-15 06:42
I also tested version 1.08.00 and can not reproduce the problems anymore.
Tested with mobile browser, android app and latest chrome browser.

Thanks, now I can finally use my new dashboard.
