### ISSUE TITLE
Tap action for navigation does not work

### ISSUE THREAD

**Issue by amblyo** [marcokreeft87/room-card#233] opened 2023-05-17 06:58 UTC
**Which version of Room Card?**
1.07.21

**Describe the bug**
Tap action does not work

**To Reproduce**
My code:
      type: custom:room-card
      title: Markplan
      entity: light.markplan
      show_icon: true
      tap_action:
        action: navigate
        navigation_path: /lovelace-rum/markplan

When i remove the entity line it works.

**Expected behavior**
Nothing hapens when i click on the card. All was working before update.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcokreeft87** [comment] 2023-05-17 08:31
Duplicate of https://github.com/marcokreeft87/room-card/issues/232 but with extra info

**Comment by marcokreeft87** [comment] 2023-05-17 09:02
Should be fixed in 1.07.22

**Closed** 2023-05-17 09:25 UTC
Labels: bug
