### ISSUE TITLE
switch state not updating when turning on/off

### ISSUE THREAD

**Issue by labaland** [marcokreeft87/room-card#244] opened 2023-06-02 21:39 UTC
switch and input_boolean do not change state when turning on or off
I have to refresh the page to see new state.

my card:

```
  - entities:
      - entity: input_boolean.ac_change_settings
        show_icon: true
        name: Laddare
        icon: mdi:cellphone-charging
        show_state: true
        tap_action:
          action: toggle
```

**Comment by marcokreeft87** [comment] 2023-06-05 07:27
There must be something weird about that input_boolean.ac_change_settings than. Its working on my HA with multiple input_booleans. Is it a template entity or something like that? Im going to close this since its not a bug. But I'll still respond and try to help you

**Closed by marcokreeft87** 2023-06-05 07:27 UTC
Labels: bug

**Comment by kimzeuner** [comment] 2023-09-26 10:01
Have you been able to solve the problem ? 
i have a similar problem with the hide_if function. The state of the entity changes from on to off or the other way around but the horizontal-stack does not hide/appear when the state changes. As already mentioned in the initial post the new state is only taken after a refresh of the page.

`type: custom:room-card
title: Wohnzimmer
icon: mdi:sofa
show_icon: true
entity: cover.rollo_wohnzimmer
tap_action:
  action: none
double_tap_action:
  action: none
hold_action:
  action: none
cards:
  - type: horizontal-stack
    hide_if:
      conditions:
        - condition: equals
          value: 'off'
          entity: input_boolean.shortcut_rollo_wohnzimmer`
